### ISSUE TITLE
Mime File Type

### ISSUE THREAD

**Issue by bonnebulle** [rico345100/socket.io-file-client#2]
Hello
When I try to upload a file (image) I have this error (console)
```
Error! Error: Not Acceptable file type image/jpeg of Bibliographie ROTATE_Page_3.jpg. Type must be one of these: image/jpg, image/png, image/gif
Trace de la pile :
_upload/fileReader.onloadend@http://localhost:4000/socket.io-file-client.js:47:32
```
I just updated Npm (+node), so, maybe it is a incompatibility.
If not, where can I "force" to upload all images types?
Right now, just png are allowed.
Thanks

**Comment by rico345100** [comment]
Hello, @vb078. Which version of socket.io-file-client and socket.io-file you are using? And could you copy and paste your uploading part of source code? I will check this module but more information makes easier to solve :)

**Comment by rico345100** [comment]
In Socket.io-file, limiting MIME type logic is working something like this:

1. First, server sends "acceptable mime type list" which you specified in Socket.io-file(server).
2. In Client, before uploads a file, it checks mime type in client(which received from server). If it is not acceptable, it doesn't send the file and throw error message.
3. In Server, after uploads a file, it checks it's mime type immediately. If it's not acceptable, it removes this file and throw error message which is not acceptable mime type or something.
4. If it is acceptable, invokes completed event.

So, I guess that you want to "accept" every image types, not just type everything manually right? Basically there is no functionality for that now, because there are plenty of image mime types and I couldn't add at all.

If you want to accept any kind of image file, you have to write every mime types into "accept" list in Socket.io-file(server) manually.

I think adding a new feature that supports something like "regex pattern" in acceptable list will great, I will consider to adding that. Thanks.

**Comment by rico345100** [comment]
I'm closing this because you didn't any responses, but feel free to open this if you need some help.

**Comment by bonnebulle** [comment]
Thanks, I find where my uploader disallowed this MIME.
